version: '3'
services:
  app:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ./:/app/
    command: bash -c "rm -rf /app/tmp/pids/server.pid &&
                      rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgres/data
    environment:
      POSTGRES_USERNAME: username
      POSTGRES_PASSWORD: password
